#!/bin/bash
# Copyright 2011, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

nodes_wo_swift=$(knife_node_find '(NOT roles:swift-storage)' FQDN)
admin_node=$(knife_node_find 'roles:crowbar' FQDN)
nodes_wo_swift="$(echo "${nodes_wo_swift}" | grep -v "${admin_node}" | head -n 1)"
sed -e '/"elements": {/,/}/{/"cinder-volume": \[/,/]/ s/\".*\.smoke\.test\"/'${nodes_wo_swift}'/}'

